/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.Department;
import Entity.Employee;
import Entity.Employee_Phones;
import company1.Tools;
import controls.JTextBox;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author owner
 */
public class FRMEmployee extends javax.swing.JFrame {

    /**
     * Creates new form FRMEmployee
     */
    public FRMEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEmpNo = new controls.JTextBox(15);
        txtEmpNam = new controls.JTextBox(15);
        txtEmpSal = new controls.JTextBox(15);
        cbxDept = new controls.JMyCombo();
        btnAdd = new controls.JMyButton();
        btnUpd = new controls.JMyButton();
        btnDel = new controls.JMyButton();
        btnFind = new controls.JMyButton();
        btnAll = new controls.JMyButton();
        btnClear = new controls.JMyButton();
        jLabel11 = new javax.swing.JLabel();
        rdoNum = new javax.swing.JRadioButton();
        rdoName = new javax.swing.JRadioButton();
        rdoAddre = new javax.swing.JRadioButton();
        rdoSalar = new javax.swing.JRadioButton();
        rdoHier = new javax.swing.JRadioButton();
        rdoBirth = new javax.swing.JRadioButton();
        rdoDept = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();
        jMyButton8 = new controls.JMyButton();
        jLabel12 = new javax.swing.JLabel();
        btnBack = new controls.JMyButton();
        btnAddDept = new controls.JMyButton();
        txtSearch = new controls.JTextBox(20);
        txtEmpAdd = new controls.JTextBox(15);
        jLabel9 = new javax.swing.JLabel();
        txtphons = new controls.JTextBox(15);
        AddPho = new controls.JMyButton();
        btnRemovPho = new controls.JMyButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhone = new javax.swing.JTable();
        rdoPhone = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        EmtLabl = new javax.swing.JLabel();
        txtBirthDate = new com.toedter.calendar.JDateChooser();
        txtHirungDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("EMPLOYEE");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("NUMBER          :");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("NAME               :");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("SALARY           :");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("HIRING DATE   :");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("BIRTH DATE    :");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("DEPARTMENT :");

        txtEmpNo.setEditable(false);

        txtEmpNam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmpNamKeyPressed(evt);
            }
        });

        txtEmpSal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmpSalKeyPressed(evt);
            }
        });

        cbxDept.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbxDeptKeyPressed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpd.setText("Update");
        btnUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdActionPerformed(evt);
            }
        });

        btnDel.setText("Delate");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnAll.setText("All");
        btnAll.setEnabled(false);
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });

        btnClear.setText("clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Search By");

        rdoNum.setSelected(true);
        rdoNum.setText("num");

        rdoName.setText("name");

        rdoAddre.setText("Address");

        rdoSalar.setText("Salary");

        rdoHier.setText("Hiering ");

        rdoBirth.setText("Birth");

        rdoDept.setText("Dept");

        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name", "Address", "Salary", "Hiring Date", "Birth Day", "Department Number", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmp.setAutoscrolls(false);
        tblEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpMouseClicked(evt);
            }
        });
        tblEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblEmpKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmp);

        jMyButton8.setText("Search");
        jMyButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyButton8ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("ADDRESS        :");

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddDept.setText("+");
        btnAddDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDeptActionPerformed(evt);
            }
        });

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        txtEmpAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmpAddKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("PHONE :");

        txtphons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphonsActionPerformed(evt);
            }
        });
        txtphons.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtphonsKeyPressed(evt);
            }
        });

        AddPho.setText("Add");
        AddPho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPhoActionPerformed(evt);
            }
        });

        btnRemovPho.setText("Remove");
        btnRemovPho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovPhoActionPerformed(evt);
            }
        });

        tblPhone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PHONES"
            }
        ));
        tblPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhoneMouseClicked(evt);
            }
        });
        tblPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblPhoneKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblPhone);

        rdoPhone.setText("Phone");

        jLabel10.setText("F3: 削除");

        jLabel13.setText("F4: 更新");

        jLabel14.setText("F5: 追加");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEmpSal))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEmpAdd))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(9, 9, 9)
                                            .addComponent(txtEmpNam))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cbxDept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnAddDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(4, 4, 4)
                                            .addComponent(txtphons, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5)
                                            .addComponent(AddPho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnRemovPho, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(txtHirungDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtBirthDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(1, 1, 1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAll, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(EmtLabl, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoAddre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoSalar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jMyButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoHier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoBirth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoDept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(586, 586, 586)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEmpNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtEmpAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(txtEmpSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtHirungDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbxDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtphons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddPho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemovPho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoNum)
                            .addComponent(rdoName)
                            .addComponent(rdoAddre)
                            .addComponent(rdoSalar)
                            .addComponent(rdoHier)
                            .addComponent(rdoBirth)
                            .addComponent(rdoDept)
                            .addComponent(jLabel11)
                            .addComponent(rdoPhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMyButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmtLabl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(jLabel13)
                                .addComponent(jLabel10)))))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdActionPerformed
        setValues();
        emp.Update();
        //UpDate{
        Phones.setEmpno(Integer.parseInt(txtEmpNo.getText()));
        //Delete Phones
        Phones.DeleteByEmp();
        //Add Phones
        for (int x = 0; x < tblPhone.getRowCount(); x++) {
            Phones.setPhone(tblPhone.getValueAt(x, 0).toString());
            Phones.Add();
        }//}
        clearData();
        emp.getAllRoes(tblEmp);
    }//GEN-LAST:event_btnUpdActionPerformed
    public void setValues() {
        emp.setEmpNo(Integer.parseInt(txtEmpNo.getText()));
        emp.setEmpName(txtEmpNam.getText());
        emp.setAddress(txtEmpAdd.getText());
        emp.setSalary(Double.parseDouble(txtEmpSal.getText()));

        //JCALANDER
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        String HDate = String.valueOf(f.format(txtHirungDate.getDate()));
        String BDate = String.valueOf(f.format(txtBirthDate.getDate()));
        emp.setHiringDate(HDate);
        emp.setBirthDate(BDate);

        String dName = cbxDept.getSelectedItem().toString();
        String dNo = dept.getValueByName(dName);
        emp.setDeptNo(Integer.parseInt(dNo));
    }

    Employee_Phones Phones = new Employee_Phones();
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        setValues();
        emp.Add();
        //Add Phones
        Phones.setEmpno(Integer.parseInt(txtEmpNo.getText()));
        for (int x = 0; x < tblPhone.getRowCount(); x++) {
            Phones.setPhone(tblPhone.getValueAt(x, 0).toString());
            Phones.Add();
        }
        //#284
        clearData();
        emp.getAllRoes(tblEmp);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        if (Tools.ConfirmMsg("DO YOU WANT TO DELETE ? ")) {
            //Delete Phones
            Phones.setEmpno(Integer.parseInt(txtEmpNo.getText()));
            Phones.DeleteByEmp();

            setValues();
            emp.Delete();
            clearData();
            emp.getAllRoes(tblEmp);
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String EmpNo = (String) Tools.InputBox("Enter Employee number");
        int EmNO = Integer.parseInt(EmpNo);

        emp.setEmpNo(EmNO);
        emp.getOneRow(tblEmp);
    }//GEN-LAST:event_btnFindActionPerformed
    Department dept = new Department();
    Employee emp = new Employee();
    private void btnAddDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDeptActionPerformed
        int DeptNo = Integer.parseInt(dept.getAutoNumber());
        String Deptname = (String) Tools.InputBox("inter DepartNMe");
        String Location = (String) Tools.InputBox(" imter Location");

        if ("".equals(Deptname) || "".equals(Location)) {
            Tools.msgBox(">>Valiuse is Null-The Adding is cancele<<");
        } else {
            dept.setDeptno(DeptNo);
            dept.setDeptName(Deptname);
            dept.setLocation(Location);
            dept.Add();

            DB.Go.fillCombo("department", "DEPARTNAME", cbxDept);
        }
    }//GEN-LAST:event_btnAddDeptActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        Tools.openForm(new FrmMan());
    }//GEN-LAST:event_btnBackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btnGroup.add(rdoNum);
        btnGroup.add(rdoName);
        btnGroup.add(rdoAddre);
        btnGroup.add(rdoSalar);
        btnGroup.add(rdoHier);
        btnGroup.add(rdoBirth);
        btnGroup.add(rdoDept);
        btnGroup.add(rdoPhone);

        DB.Go.fillCombo("department", "DEPARTNAME", cbxDept);
        emp.getAllRoes(tblEmp);
        clearData();

        tblEmp.getTableHeader().setReorderingAllowed(false);
        tblPhone.getTableHeader().setReorderingAllowed(false);

    }//GEN-LAST:event_formWindowOpened
    private void clearData() {
        Tools.clearText(this);
        txtEmpNo.setText(emp.getAutoNumber());
        btnAdd.setEnabled(true);
        btnUpd.setEnabled(false);
        btnDel.setEnabled(false);
        btnRemovPhoActionPerformed(null);
        txtEmpNam.requestFocus();
    }
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearData();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        emp.getAllRoes(tblEmp);
    }//GEN-LAST:event_btnAllActionPerformed

    private void tblEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpMouseClicked
        try {
            int row = tblEmp.getSelectedRow();
            txtEmpNo.setText(tblEmp.getValueAt(row, 0).toString());
            txtEmpNam.setText(tblEmp.getValueAt(row, 1).toString());
            txtEmpAdd.setText(tblEmp.getValueAt(row, 2).toString());
            txtEmpSal.setText(tblEmp.getValueAt(row, 3).toString());

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date dateH = sdf.parse(tblEmp.getValueAt(row, 4).toString());
            Date dateB = sdf.parse(tblEmp.getValueAt(row, 5).toString());

            txtHirungDate.setDate(dateH);
            txtBirthDate.setDate(dateB);
            cbxDept.setSelectedItem(tblEmp.getValueAt(row, 7));

            Phones.setEmpno(Integer.parseInt(txtEmpNo.getText()));
            Phones.getAllRoes(tblPhone);

            btnAdd.setEnabled(false);
            btnUpd.setEnabled(true);
            btnDel.setEnabled(true);

        } catch (Exception ex) {
            Tools.msgBox(ex.getMessage());
        }
    }//GEN-LAST:event_tblEmpMouseClicked
    private String getLike() {
        return " like'%" + txtSearch.getText() + "%'";
    }
    private void jMyButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyButton8ActionPerformed
        // Probleme ici ADDRESS not fanction corect
        String strSearch = "select * from employee_data where";
        if (rdoNum.isSelected()) {
            strSearch += " NUMBER" + getLike();
        } else if (rdoName.isSelected()) {
            strSearch += " NAME" + getLike();
        } else if (rdoAddre.isSelected()) {
            strSearch += " ADDRESS" + getLike();
        } else if (rdoSalar.isSelected()) {
            strSearch += " SALARY" + getLike();
        } else if (rdoHier.isSelected()) {
            strSearch += " HIRING_DATE" + getLike();
        } else if (rdoBirth.isSelected()) {
            strSearch += " DATE_OF_BIRTH" + getLike();
        } else if (rdoDept.isSelected()) {
            strSearch += " DEPARTMENT_NO" + getLike()
                    + " or department" + getLike();
        } else {
            String strEmpNum = Phones.getEmpnoByPhone(txtSearch.getText());
            strSearch += " Number like '%" + strEmpNum + "%'";
        }
        emp.getCustemRows(strSearch, tblEmp);
    }//GEN-LAST:event_jMyButton8ActionPerformed

    private void AddPhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPhoActionPerformed
        //#283
        DefaultTableModel mod = (DefaultTableModel) tblPhone.getModel();
        mod.addRow(new Object[]{txtphons.getText()});//moraja3a(Tble AddRow)
        txtphons.setText("");
        txtphons.requestFocus();//Cersor ;
    }//GEN-LAST:event_AddPhoActionPerformed

    private void btnRemovPhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovPhoActionPerformed

        DefaultTableModel mod = (DefaultTableModel) tblPhone.getModel();
        mod.setNumRows(0);
    }//GEN-LAST:event_btnRemovPhoActionPerformed

    private void txtphonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphonsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphonsActionPerformed

    private void tblPhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhoneMouseClicked
        try {
            int row = tblPhone.getSelectedRow();
            txtphons.setText(tblPhone.getValueAt(row, 0).toString());
        } catch (Exception ex) {
            Tools.msgBox(ex.getMessage());
        }
    }//GEN-LAST:event_tblPhoneMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F5) {
            setValues();
            emp.Add();
            //Add Phones
            Phones.setEmpno(Integer.parseInt(txtEmpNo.getText()));
            for (int x = 0; x < tblPhone.getRowCount(); x++) {
                Phones.setPhone(tblPhone.getValueAt(x, 0).toString());
                Phones.Add();
            }
            //#284
            clearData();
            emp.getAllRoes(tblEmp);
        }
    }//GEN-LAST:event_formKeyPressed
    public void PressBtnToAddOrUpdete(KeyEvent evt, String EmtTxt, JTextField txtfield) {

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtfield.requestFocus();
        }

        if (evt.getKeyCode() == KeyEvent.VK_F5) {
            if ("".equals(EmtTxt)) {
                Tools.msgBox("enter Values");
            } else {
                setValues();
                emp.Add();

                Phones.setEmpno(Integer.parseInt(txtEmpNo.getText()));
                for (int x = 0; x < tblPhone.getRowCount(); x++) {
                    Phones.setPhone(tblPhone.getValueAt(x, 0).toString());
                    Phones.Add();
                }
            }
            clearData();
            emp.getAllRoes(tblEmp);
        }
        if (evt.getKeyCode() == KeyEvent.VK_F4) {
            if ("".equals(EmtTxt)) {
                Tools.msgBox("enter Values");
            } else {
                setValues();
                emp.Update();
                //UpDate{
                Phones.setEmpno(Integer.parseInt(txtEmpNo.getText()));
                //Delete Phones
                Phones.DeleteByEmp();
                //Add Phones
                for (int x = 0; x < tblPhone.getRowCount(); x++) {
                    Phones.setPhone(tblPhone.getValueAt(x, 0).toString());
                    Phones.Add();
                }
                clearData();
                emp.getAllRoes(tblEmp);
            }
        }
    }
    private void txtEmpNamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpNamKeyPressed
        String EmtVal = txtEmpNam.getText();
        PressBtnToAddOrUpdete(evt, EmtVal, txtEmpAdd);
    }//GEN-LAST:event_txtEmpNamKeyPressed

    private void txtEmpAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpAddKeyPressed
        String EmtVal = txtEmpAdd.getText();
        PressBtnToAddOrUpdete(evt, EmtVal, txtEmpSal);
    }//GEN-LAST:event_txtEmpAddKeyPressed

    private void txtEmpSalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpSalKeyPressed
        String EmtVal = txtEmpNam.getText();
        PressBtnToAddOrUpdete(evt, EmtVal, txtphons);
    }//GEN-LAST:event_txtEmpSalKeyPressed

    private void cbxDeptKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxDeptKeyPressed
        String EmtVal = cbxDept.getSelectedItem().toString();
    }//GEN-LAST:event_cbxDeptKeyPressed

    private void txtphonsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphonsKeyPressed
        String emtValPho = txtphons.getText();
        String emtValNa = txtEmpNam.getText();

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ("".equals(emtValPho)) {
                Tools.msgBox("電話番号を入力してください");
            } else if ("".equals(emtValNa)) {
                Tools.msgBox("社員の名前を入力してください");
            } else {
                DefaultTableModel mod = (DefaultTableModel) tblPhone.getModel();
                mod.addRow(new Object[]{txtphons.getText()});//moraja3a(Tble AddRow)
                txtphons.setText("");
                txtphons.requestFocus();//Cersor ;
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_F4) {
            if ("".equals(emtValNa) & "".equals(emtValPho)) {
                Tools.msgBox("データ入力してください");
            } else {
                setValues();
                emp.Update();
                Phones.setEmpno(Integer.parseInt(txtEmpNo.getText()));
                Phones.DeleteByEmp();
                for (int x = 0; x < tblPhone.getRowCount(); x++) {
                    Phones.setPhone(tblPhone.getValueAt(x, 0).toString());
                    Phones.Add();
                }
                clearData();
                emp.getAllRoes(tblEmp);
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_F5) {
            if ("".equals(emtValNa) & "".equals(emtValPho)) {
                Tools.msgBox("データ入力してください");
            } else {
                setValues();
                emp.Add();
                Phones.setEmpno(Integer.parseInt(txtEmpNo.getText()));
                for (int x = 0; x < tblPhone.getRowCount(); x++) {
                    Phones.setPhone(tblPhone.getValueAt(x, 0).toString());
                    Phones.Add();
                }
                clearData();
                emp.getAllRoes(tblEmp);
            }
        }

    }//GEN-LAST:event_txtphonsKeyPressed

    private void tblPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblPhoneKeyPressed

    }//GEN-LAST:event_tblPhoneKeyPressed

    private void tblEmpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblEmpKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F3) {
            if (Tools.ConfirmMsg("DO YOU WANT TO DELETE ? "));
            //Delete Phones
            Phones.setEmpno(Integer.parseInt(txtEmpNo.getText()));
            Phones.DeleteByEmp();

            setValues();
            emp.Delete();
            clearData();
            emp.getAllRoes(tblEmp);
        }
    }//GEN-LAST:event_tblEmpKeyPressed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Probleme ici ADDRESS not fanction corect
            String strSearch = "select * from employee_data where";
            if (rdoNum.isSelected()) {
                strSearch += " NUMBER" + getLike();
            } else if (rdoName.isSelected()) {
                strSearch += " NAME" + getLike();
            } else if (rdoAddre.isSelected()) {
                strSearch += " ADDRESS" + getLike();
            } else if (rdoSalar.isSelected()) {
                strSearch += " SALARY" + getLike();
            } else if (rdoHier.isSelected()) {
                strSearch += " HIRING_DATE" + getLike();
            } else if (rdoBirth.isSelected()) {
                strSearch += " DATE_OF_BIRTH" + getLike();
            } else if (rdoDept.isSelected()) {
                strSearch += " DEPARTMENT_NO" + getLike()
                        + " or department" + getLike();
            } else {
                String strEmpNum = Phones.getEmpnoByPhone(txtSearch.getText());
                strSearch += " Number like '%" + strEmpNum + "%'";
            }
            emp.getCustemRowAndShowLabel(strSearch, tblEmp, EmtLabl);
        }        
    }//GEN-LAST:event_txtSearchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyButton AddPho;
    private javax.swing.JLabel EmtLabl;
    private controls.JMyButton btnAdd;
    private controls.JMyButton btnAddDept;
    private controls.JMyButton btnAll;
    private controls.JMyButton btnBack;
    private controls.JMyButton btnClear;
    private controls.JMyButton btnDel;
    private controls.JMyButton btnFind;
    private javax.swing.ButtonGroup btnGroup;
    private controls.JMyButton btnRemovPho;
    private controls.JMyButton btnUpd;
    private controls.JMyCombo cbxDept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private controls.JMyButton jMyButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdoAddre;
    private javax.swing.JRadioButton rdoBirth;
    private javax.swing.JRadioButton rdoDept;
    private javax.swing.JRadioButton rdoHier;
    private javax.swing.JRadioButton rdoName;
    private javax.swing.JRadioButton rdoNum;
    private javax.swing.JRadioButton rdoPhone;
    private javax.swing.JRadioButton rdoSalar;
    private javax.swing.JTable tblEmp;
    private javax.swing.JTable tblPhone;
    private com.toedter.calendar.JDateChooser txtBirthDate;
    private javax.swing.JTextField txtEmpAdd;
    private javax.swing.JTextField txtEmpNam;
    private javax.swing.JTextField txtEmpNo;
    private javax.swing.JTextField txtEmpSal;
    private com.toedter.calendar.JDateChooser txtHirungDate;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtphons;
    // End of variables declaration//GEN-END:variables
}
