/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import company1.Tools;
import java.awt.event.KeyEvent;

/**
 *
 * @author owner
 */
public class FrmMan extends javax.swing.JFrame {

    /**
     * Creates new form FrmMan
     */
    public FrmMan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDept = new controls.JMyButton();
        jMyButton1 = new controls.JMyButton();
        jLabel1 = new javax.swing.JLabel();
        btnDept1 = new controls.JMyButton();
        btnProj = new controls.JMyButton();
        btnProj1 = new controls.JMyButton();
        btnReport = new controls.JMyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDept.setText("DEPARTMENT 1");
        btnDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeptActionPerformed(evt);
            }
        });
        btnDept.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDeptKeyPressed(evt);
            }
        });

        jMyButton1.setText("EXIT");
        jMyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel1.setText("MAIN FORM");

        btnDept1.setText("EMPLOYEE 2");
        btnDept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDept1ActionPerformed(evt);
            }
        });
        btnDept1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDept1KeyPressed(evt);
            }
        });

        btnProj.setText("PROJECT 3");
        btnProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjActionPerformed(evt);
            }
        });
        btnProj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnProjKeyPressed(evt);
            }
        });

        btnProj1.setText("WORKON 4");
        btnProj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProj1ActionPerformed(evt);
            }
        });
        btnProj1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnProj1KeyPressed(evt);
            }
        });

        btnReport.setText("報告 5");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        btnReport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnReportKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jMyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(399, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(90, 90, 90))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProj1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProj, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDept1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDept, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDept1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jMyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeptActionPerformed
        this.dispose();
        Tools.openForm(new FRMDepartment());
    }//GEN-LAST:event_btnDeptActionPerformed

    private void btnDept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDept1ActionPerformed
        this.dispose();
        Tools.openForm(new FRMEmployee());
    }//GEN-LAST:event_btnDept1ActionPerformed

    private void jMyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMyButton1ActionPerformed

    private void btnProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjActionPerformed
        this.dispose();
        Tools.openForm(new FRMProject());
    }//GEN-LAST:event_btnProjActionPerformed

    private void btnProj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProj1ActionPerformed
        this.dispose();
        Tools.openForm(new FRMWorkon());
    }//GEN-LAST:event_btnProj1ActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        this.dispose();
        Tools.openForm(new FRMReports());
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnDeptKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDeptKeyPressed
        KeyPress(evt);
    }//GEN-LAST:event_btnDeptKeyPressed

    private void btnDept1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDept1KeyPressed
        KeyPress(evt);
    }//GEN-LAST:event_btnDept1KeyPressed

    private void btnProjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnProjKeyPressed
        KeyPress(evt);
    }//GEN-LAST:event_btnProjKeyPressed

    private void btnProj1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnProj1KeyPressed
        KeyPress(evt);
    }//GEN-LAST:event_btnProj1KeyPressed

    private void btnReportKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnReportKeyPressed
        KeyPress(evt);
    }//GEN-LAST:event_btnReportKeyPressed
    public void KeyPress(KeyEvent Evt) {
        switch (Evt.getKeyCode()) {
            case KeyEvent.VK_1:
                Tools.openForm(new FRMDepartment());
                this.dispose();
                break;
            case KeyEvent.VK_2:
                Tools.openForm(new FRMEmployee());
                this.dispose();
                break;
            case KeyEvent.VK_3:
                Tools.openForm(new FRMProject());
                this.dispose();
                break;
            case KeyEvent.VK_4:
                Tools.openForm(new FRMWorkon());
                this.dispose();
                break;
            case KeyEvent.VK_5:
                Tools.openForm(new FRMReports());
                this.dispose();
                break;
            case KeyEvent.VK_BACK_SPACE:
                Tools.openForm(new frmlogen());
                this.dispose();
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyButton btnDept;
    private controls.JMyButton btnDept1;
    private controls.JMyButton btnProj;
    private controls.JMyButton btnProj1;
    private controls.JMyButton btnReport;
    private javax.swing.JLabel jLabel1;
    private controls.JMyButton jMyButton1;
    // End of variables declaration//GEN-END:variables
}
