/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;
/*
import Entity.Department;
import Entity.Employee;
import Entity.Employee_Phones;
import Entity.Project;
import Entity.Workon;
*/
import company1.Tools;
import Entity.*;// ol Entity Touhdar
/**
 *
 * @author owner
 */
public class frmTest extends javax.swing.JFrame {

    /**
     * Creates new form frmTest
     */
    public frmTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btntestdept = new controls.JMyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        jMyButton1 = new controls.JMyButton();
        btntestEmp = new controls.JMyButton();
        btntestEmpPhon = new controls.JMyButton();
        btntestEmpPhon1 = new controls.JMyButton();
        btnTestWorkon = new controls.JMyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btntestdept.setText("Test Department");
        btntestdept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntestdeptActionPerformed(evt);
            }
        });

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl1);

        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "	EMPNO", "EMPNAME", "ADDRESS", "タイトル 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl2);

        jMyButton1.setText("MessegeForm");
        jMyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyButton1ActionPerformed(evt);
            }
        });

        btntestEmp.setText("Test Employee");
        btntestEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntestEmpActionPerformed(evt);
            }
        });

        btntestEmpPhon.setText("Test EmployeePhon");
        btntestEmpPhon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntestEmpPhonActionPerformed(evt);
            }
        });

        btntestEmpPhon1.setText("Test Poject");
        btntestEmpPhon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntestEmpPhon1ActionPerformed(evt);
            }
        });

        btnTestWorkon.setText("Test Workon");
        btnTestWorkon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestWorkonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btntestEmpPhon1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(btnTestWorkon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(592, 592, 592)
                        .addComponent(jMyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btntestdept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btntestEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btntestEmpPhon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(186, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(43, 43, 43)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btntestdept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntestEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntestEmpPhon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jMyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btntestEmpPhon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTestWorkon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(186, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntestdeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntestdeptActionPerformed
        Department dept = new Department();
        //dept.setDeptno();
        //dept.setDeptName("Is23");
        //dept.setLocation("kori");
        //dept.Add();
        //dept.Update();
        //dept.Delete();
        //dept.getAllRoes(tbl2);
        //Tools.msgBox(dept.getAutoNumber());
        //dept.getCustemRows("select * from department", tbl2);
        // dept.getOneRow(tbl2);
        //Tools.msgBox(dept.getValueByName("SDF"));//↓
        //Tools.msgBox(dept.getValueByNumber("2"));//↑

    }//GEN-LAST:event_btntestdeptActionPerformed

    private void jMyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyButton1ActionPerformed
        boolean confirm = Tools.ConfirmMsg("aaaa?");
        if (confirm) {
            Tools.msgBox("yes");
        } else {
            Tools.msgBox("Other");
        }

    }//GEN-LAST:event_jMyButton1ActionPerformed

    private void btntestEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntestEmpActionPerformed
        Employee emp = new Employee();
        /* emp.setEmpNo(3);
        emp.setEmpName("Darouy Housin3");
        emp.setAddress("hasaniya3");
        emp.setSalary(200023);
        emp.setBirthDate("1990-02-03");
        emp.setHiringDate("2010-03-14");
         emp.setDeptNo(1);*/

        //emp.Add();
        //emp.Update();
        //emp.Delete
        //emp.getAllRoes(tbl2);//JTABL COLUMNS CONTE IS NOT THE SIME OF QUIRY COLOMNS CONTE
        //Tools.msgBox(emp.getAutoNumber());
        //emp.getCustemRows("select * from employee", tbl2);//moraja3a
        //emp.getOneRow(tbl2);//JTABL COLUMNS CONTE IS NOT THE SIME OF QUIRY COLOMNS CONTE
        // Tools.msgBox( emp.getValueByName("krimo"));moraja3a
        //Tools.msgBox(emp.getValueByNumber("1"));//moraja3a
    }//GEN-LAST:event_btntestEmpActionPerformed

    private void btntestEmpPhonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntestEmpPhonActionPerformed
        //Employee_Phones phon = new Employee_Phones();
        // phon.setEmpno(1);
        // phon.setPhone("002");
        //phon.Add();
        //phon.Delete();
        // phon.DeleteByEmp();

    }//GEN-LAST:event_btntestEmpPhonActionPerformed

    private void btntestEmpPhon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntestEmpPhon1ActionPerformed
        Project Pro = new Project();
        Pro.setProjectNo(1);
        // Pro.setProjectName("se Devlopt_OQ3");
        // Pro.setLocation("casablanca3");
        //Pro.setDeptNo(2);
        //Pro.Add();
        //Pro.Update();
        //Pro.Delete();
        //Pro.getAutoNumber();
        //Pro.getAllRoes(tbl2);
        //Pro.getOneRow(tbl2);
       // Pro.getCustemRows("select * from project_data", tbl2);
        //Tools.msgBox(Pro.getValueByNumber("se Devlopt_OQpp"));
        //Tools.msgBox(Pro.getValueByName("1"));
    }//GEN-LAST:event_btntestEmpPhon1ActionPerformed

    private void btnTestWorkonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestWorkonActionPerformed
        Workon work = new Workon();
        
        work.setEmpNo(2);
        work.setProjNo(2);
        
        //work.Add();
        //work.Delete();
        //work.getAllRoes(tbl2);
        //work.getOneRow(tbl2);
        //work.getCustemRows("select * from workon_data", tbl2);
    }//GEN-LAST:event_btnTestWorkonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyButton btnTestWorkon;
    private controls.JMyButton btntestEmp;
    private controls.JMyButton btntestEmpPhon;
    private controls.JMyButton btntestEmpPhon1;
    private controls.JMyButton btntestdept;
    private controls.JMyButton jMyButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    // End of variables declaration//GEN-END:variables
}
